server:
  port: 8080
spring:
  datasource:
    master:
      password: devuser
      url: dbc:mysql://192.168.1.174:3306/questionnaire_center?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT
      driver-class-name: com.mysql.jdbc.Driver
      username: devuser
      type: com.zaxxer.hikari.HikariDataSource
    cluster:
      - key: slave1
        password: devuser
        url: jdbc:mysql://192.168.1.201:3306/dsp_staff_pool_00?useSSL=false&serverTimezone=GMT%2B8&useUnicode=true&amp&characterEncoding=utf-8
        idle-timeout: 20000
        driver-class-name: com.mysql.jdbc.Driver
        username: devuser
        type: com.zaxxer.hikari.HikariDataSource
      - key: slave2
        password: devuser
        url: jdbc:mysql://192.168.1.201:3306/dsp_staff_pool_01?useSSL=false&serverTimezone=GMT%2B8&useUnicode=true&amp&characterEncoding=utf-8
        driver-class-name: com.mysql.jdbc.Driver
        username: devuser
mybatis:
  mapper-locations: classpath:/mybatis/mapper/*.xml
  config-location:  classpath:/mybatis/config/mybatis-config.xml